version: 0.2
            
phases:
  install:
    commands:
      - echo "Installation"
  pre_build:
    commands:
      - command
      - command
  build:
    commands:
      - docker pull rcommande/blog
  #post_build:
  #  commands:
  #    - command
  #    - command
#artifacts:
  #files:
    #- location
    #- location
  #discard-paths: yes
  #base-directory: location
